# ใช้ Nginx image จาก Docker Hub
FROM nginx:alpine

# คัดลอกไฟล์คอนฟิกไปยัง container
COPY default.conf /etc/nginx/conf.d/default.conf

# คัดลอก SSL Certificates ไปยัง container
COPY /home/ssl_csr/certnew-bualuangstaffinfo.sawasdee.brk1_2024-2026.cer /etc/ssl/certs/all_certificate.crt
COPY /home/ssl_csr/private.key /etc/ssl/private/privatekey.key
COPY /home/ssl_csr/BLS-Root-CA.cer /etc/ssl/certs/BLS-Root-CA.crt

# เปิดพอร์ต 80 และ 443
EXPOSE 80 443

# คำสั่งเริ่มต้นของ Nginx
CMD ["nginx", "-g", "daemon off;"]
