# ใช้ Nginx image จาก Docker Hub
FROM nginx:alpine

# คัดลอกไฟล์คอนฟิกไปยัง container
COPY default.conf /etc/nginx/conf.d/default.conf
COPY bualuangstaffinfo.sawasdee.brk1.crt /etc/nginx/
COPY private.key /etc/nginx/

# เปิดพอร์ต 80 และ 443
EXPOSE 80 443

# คำสั่งเริ่มต้นของ Nginx
CMD ["nginx", "-g", "daemon off;"]
